#!/bin/bash

./script/build-server

# Set needed variables
export ENV=Development
export APIKEY=trenzalore

# Spoofed dev values
export PGHOST=localhost
export PGPORT=5432
export PGUSER=master_explorer_user
export PGPASS=handmina
export PGDATABASE=master_explorer

./dist-newstyle/build/x86_64-linux/ghc-8.0.2/server-0.1.0.0/c/server/build/server/server
#./server-result/bin/server

